### ISSUE TITLE
how to run django-todo in mezzanine

### ISSUE THREAD

**Issue by datatalking** [shacker/django-todo#36]
Would this app work on something that is also written django or more specifically in mezzanine? I have a django page up and running, but it badly needs a todo app like this. I am interested in reposting to this page and mezzanine a link when I figure out how as well as the code.

**Comment by shacker** [comment]
@datatalking django-todo is *specifically* written as a reusable app, i.e. suitable for being dropped into any existing django project. I haven't tried it with mezzanine but would certainly expect it to work fine there. However, stay tuned - django-todo is in a period of very heavy development and I'm preparing to release a completely rewritten version 2.0 in the coming weeks. You might want to hold off a bit before integrating.

**Comment by shacker** [comment]
@datatalking wrt the subject line of your ticket, I'm not sure what you mean by "merge" -- think of reusable apps in Django as plugins.

**Comment by shacker** [comment]
@datatalking Yes there is absolutely a learning curve! Keep at it. I'm still not sure what your question is - again, this is a reusable app, designed to be dropped into any existing Django site. I don't know Mezzanine but if it's a "normal" Django site, this should just work. If you have questions about how to install reusable apps into Mezzanine, you should ask people on that project. 

django-todo version 2 was just released, so if you're using it, please update! (not yet pip installable, but soon).

Closing this because there's nothing here I can help you with.
