### ISSUE TITLE
Question : Additionnal fields

### ISSUE THREAD

**Issue by tboulogne** [shacker/django-todo#89]
Hello,

I just discoure your project, it's seem nice. 
A question : anyway to add additionnel field to request form ? 

Thank for help.

Regards,

Thierry

**Comment by shacker** [comment]
Hi @tboulogne - Can you be more specific what mean by "the request form?" Which form are you referring to?

**Comment by tboulogne** [comment]
Hello @shacker,

Thanks for answering. I mean the ticket form. I'm preparing a pull request with some changes. It could be more clear.

If you find this usefull, you will pull it.

Regards,

Thierry

**Comment by shacker** [comment]
I have not seen the referenced pull request come through since October, so am closing this. 

In general, if more fields are needed that would be useful to everyone, someone can propose it with specifics. Or, if there is a strong and demonstrable need to make the form more flexible so that people can add their own custom fields, we can talk about that too (though in general for something like this you would subclass the form and append your own fields).

Closing this until we have more specifics on the needs/requirements.
