### ISSUE TITLE
Great Job!  And then I am wondering that how to develop my version? 

### ISSUE THREAD

**Issue by tuhaolam** [shacker/django-todo#93]
I would like to develop as independent project, with series of task type having different format, such as operation tickets and development tickets.

**Comment by shacker** [comment]
Hi - I'm not sure what you are asking. Are you asking how to deploy Django projects in general, or something specific about this module? If you're asking about deploying Django, just google it, or join the mailing list, or look on the django subreddit or...

**Comment by tuhaolam** [comment]
I'm sorry for the confusing description as above. I wanna modify this project to a ticket management system, therefore I need know how to custom-define, and now I have almost finished development.

**Comment by shacker** [comment]
It's definitely intended to be used in a ticketing system, but you shouldn't need to fork the project or modify it in any way. If there are things you need it to do that it is not doing, please file a feature request and we'll discuss it! I hate to see people out there forking open source libraries rather than just implementing them or contributing to them.

**Comment by tuhaolam** [comment]
I feel very sorry for my mistake of  implementing this open source project in the error way. I will correct it. Thanks a lot for your forgiveness.

**Comment by shacker** [comment]
Oh no need to apologize - it's a common thing for people to do. My guideline is that you should only fork when the software doesn't need something you need it to do *and* the maintainer isn't willing to accept a change request to make it do that thing. If you fork unnecessarily you create more work for yourself, and cut yourself off from future upgrades.
