### ISSUE TITLE
Can we add a time blocking element.

### ISSUE THREAD

**Issue by datatalking** [shacker/django-todo#96]
The app has been such a great help, we are experimenting with Timeblocking or Timeboxing projects to make us more efficient in a day to day basis.

Django already has a calendar function, could we add a more cognitive function where we schedule todo tasks for specific time slots.

We could start with 1 hour or 15-minute segments in which we address a specific TODO element, this will help us coordinate meetings, collaboration with teams as well as focus the user for a small slot of time thus urgency.

I'm willing to help with the design, layout and other elements of this but I'm not highly skilled in Django.

Who likes the idea of adding time blocking or time boxing to this awesome TODO app?

**Comment by shacker** [comment]
todo already has a "Due date" option - would it be sufficient for it to be a datetime rather than a date? Or is it important for it to be a time *window*? 

I have to say, in 10+ years no one has ever requested this feature, and it's certainly not something I would use. I'm reluctant to add things that aren't commonly needed. Do you have a sense for how many organizations use this sort of "time window" workflow? Sounds so strict!

**Comment by datatalking** [comment]
My thought process is like this with time blocking.

There have been many studies that show that long periods of uninterrupted time allow for improved focus.

Also as “switching”, “changing channels” or “multitasking” are known to be bad for productivity.

This would allow the user to work on that one item and when it’s done the next step in the project moves into its place as a sort of priority inheritance.

So we would need a date and a span of time for example. When you see the dentist they book you in for a cleaning on Tuesday 3pm for 90 minutes. After that you need to reschedule if the calendar is full.

In legal world you schedule a consult with an attorney, doctors book thief time with clients. In finance we focused on having more time face to face with clients for reviews and signing of applications.

Software developers could book time in the calendar to “do market research” or whatever and people can see it lasts one hour where he is unavailable. The developer gets that required minimum time scheduled and completed as part of ongoing staying current. You could also have this time be checking email where you check email for 60 minutes from 10 am to 11am each day and then you go back to work on code.

Does that paint a better picture?

I think this would give us a highly useful feature and productive functionality that few todo apps offer.

A productive DND “I must get this done and I’m giving myself an hour of uninterrupted time to focus just on it” of sorts.

**Comment by shacker** [comment]
Hi, sorry for the delay! It's been a hectic winter. I just re-read your comment and looked again at the app. While it would not be terribly difficult to add a start time and end time to tasks, I am still concerned that this is a feature that no one has ever asked for. In a way, your request sits right at the intersection of todo apps and calendar apps. I think that what you're requesting has more kinship with calendaring apps than with todo apps, which are more focused on list making and task completion, not with scheduling. It's a fine line.

For my personal/daily/work todo use, I use Things 3, which is sort of the pinnacle of todo app sophistication, and it doesn't even support times - dates only. Which got me thinking, "If not even Things 3 supports it, it would be weird for django-todo to support it."

So I'm going to close this request, not because it's a bad idea but because it's just not the right fit. But will leave this thread here for posterity and if anyone reading this feels strongly that this would be a desirable feature, please speak up. Enough votes and I'll reconsider.
